Feature/grab
afficode/frontend pull request #73
Opened 2024-11-07 14:30 UTC by godstimedev

This pull request includes several changes to the routing, component behavior, and UI elements in the project. The most important changes focus on updating navigation paths, enhancing component functionalities, and improving the user interface.

2024-11-09 00:55 UTC, samuelchika requested changes

2024-11-09 00:55 UTC, samuelchika commented on src/components/GrabUpdateTable/index.jsx
> +	// console.log(ad);
Can you remove this lines

2024-11-09 00:55 UTC, samuelchika commented on src/components/GrabUpdateTable/index.jsx
> +	// console.log(schedulesResult?.schedules);
Can you remove this?

2024-11-09 00:55 UTC, samuelchika commented on src/components/InspectorCard/index.jsx
> +	console.log('latest', latestBooking?.date);
No `console.log()`

This line should be removed

2024-11-09 00:55 UTC, samuelchika commented on src/components/InspectorCard/index.jsx
> +	// console.log('data', data?.schedules?.owner);
This should also be removed

2024-11-09 00:55 UTC, samuelchika commented on src/components/InspectorCard/index.jsx
> +		// user_id: user.id,
This also should be removed.

2024-11-09 00:55 UTC, samuelchika commented on src/components/InspectorCard/index.jsx
> +		// console.log('formdata', formData);
We won't want to have this comments spill around the code.

2024-11-09 00:55 UTC, samuelchika commented on src/components/InspectorCard/index.jsx
> +				console.log(error);
This will be bad for production. Take this off for security measures.

2024-11-09 00:55 UTC, samuelchika commented on src/components/InspectorCard/index.jsx
> +	console.log('formik', initialValues);
And also this. It should be removed.

2024-11-09 00:55 UTC, samuelchika commented on src/components/InspectorCard/index.jsx
> +							// disabled={true}
This should be deleted.

2024-11-09 00:55 UTC, samuelchika commented on src/constants/routes.js
> +		// details: '/profile/details',
Any reason for this here?

2024-11-09 00:55 UTC, samuelchika commented on src/index.css
> +	/* border: 1px solid #cccccce5; Gray border */
Any reason for this here?

2024-11-09 00:55 UTC, samuelchika commented on src/layout/Navbar/index.jsx
> +// )}
This comments, is it for a future feature of a testing.?

If we won't need it, you can take it away.

2024-11-09 00:55 UTC, samuelchika commented on src/pages/Grabs/GrabbedProduct/Modals/InspectionSchedule/index.jsx
>  					// console.log(data);
This should be taken out

2024-11-09 00:55 UTC, samuelchika commented on src/pages/Grabs/Settings/index.jsx
>  				// console.log('Settings saved successfully!', response.data);
To be deleted

2024-11-09 00:55 UTC, samuelchika commented on src/pages/Grabs/Settings/index.jsx
>  				// Ensure to set submitting state to false after submission attempt
Remove this line.

2024-11-09 09:43 UTC, samuelchika requested changes

2024-11-09 09:43 UTC, samuelchika commented on src/components/AccountHistory/index.jsx
> +	// Helper function to format date to YYYY-MM-DD
Please take this away

2024-11-09 09:43 UTC, samuelchika commented on src/pages/Grabs/Product/index.jsx
>  								{/* Product ID:201344 */}
This should be off

2024-11-09 09:43 UTC, samuelchika commented on src/pages/Grabs/Settings/index.jsx
>  	// const validationSchema =
This should be removed too.

2024-11-09 09:43 UTC, samuelchika commented on src/pages/Grabs/Settings/index.jsx
>  				// Ensure to set submitting state to false after submission attempt
This also

2024-11-09 09:43 UTC, samuelchika commented on src/pages/Grabs/Settings/index.jsx
>  				// Ensure to set submitting state to false after submission attempt
This also

2024-11-09 17:27 UTC, godstimedev commented on src/pages/Grabs/Settings/index.jsx
>  				// Ensure to set submitting state to false after submission attempt
All fixed

2024-11-09 22:23 UTC, samuelchika requested changes

2024-11-09 22:23 UTC, samuelchika commented on src/components/AccountHistory/index.jsx
>  		// Sort the transactions by date in descending order (latest date first)
Please let's take this out.
Thanks
This will be the last one 😪

2024-11-09 22:23 UTC, samuelchika commented on src/components/GrabUpdateTable/index.jsx
> +							// console.log('latest', latestBooking);
This also should be out.
Try use the resolve button when you fix it to help me keep track of what you have fixed.

2024-11-10 22:57 UTC, samuelchika commented
![image](https://github.com/user-attachments/assets/63bfb5e6-08db-471c-bcc5-04afaaf43194)

I got the below error, and I have dropped you a message on Discord. 
Can yo review that and get back to me on that. 

Thanks.

2024-11-11 22:08 UTC, samuelchika approved these changes

2024-11-11 22:08 UTC, merged